name: Syntax Check

on:
  push:
    branches:
      - pract14
  

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Install Roslyn Analyzers
      run: dotnet tool install -g Microsoft.CodeAnalysis.FxCopAnalyzers
      
    - name: Run Roslyn Analyzers
      run: dotnet build /p:WarningLevel=6 /p:DebugType=None /p:DebugSymbols=false /p:Platform="Any CPU" /p:TreatWarningsAsErrors=true
